name: Claude Assistant
on:
  issue_comment:
    types: [created]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}